### ISSUE TITLE
Amount of users suported by Parse free quota.

### ISSUE THREAD

**Issue by guillermomuntaner** [relatedcode/NotificationChat#88]
Hi, this library and chat implementation is quite nice!

My only concern is about the amount of Parse requests/second per user this is consuming. ¿How many simultaneous users can you support with the Parse free cuota of 30req/s?

**Comment by StormFactory** [comment]
It's hard to give an exact number of users because there could be different variables depending on how many API calls you require each user to make.  

Let's assume that each user makes 100 API calls per month.  You would need 777,600 users before having to worry about paying Parse because 30reqs/s equates to 77.76 million API requests per month.

The bottom line is, once you get big enough to where you're paying Parse, you'll be able to afford the $200 per month.

You can find more of this information out on Parse's blog http://blog.parse.com/2014/04/30/parse-pricing-now-cheaper-and-simpler and https://www.parse.com/plans/faq/

**Comment by guillermomuntaner** [comment]
@StormFactory  I know how Parse quotas work. My concern is this code is quite HEAVY on number of requests (each message sent requires 1 query, N saves and 1 push). So 100API calls per month looks like a quite low number.

My point is trying to know how many users i can have for each 10req/sec block, to know if this code is scalable or not!

You just can't take for granted that when you reach the Parse limit you will be earning enough money to afford Parse. It all depends!

**Comment by StormFactory** [comment]
@guillermomuntaner Since you know how Parse's quota's work, you should know that they charge the 30 requests per second in 60 second blocks.  So it would seem that technically you could have 500 requests in 1 second as long as you don't hit 1,800 requests for that minute, you won't go over your limit.

Parse estimates 10 API calls per user.  I'm assuming the user comes back to your app 10 times a month in my previous calculation.

With your example of 1 query and 1 push, the push notification doesn't count against your 30 requests per second.  Assuming that people are typing their responses, how many messages can one person send in 1 second.  Or in 60 seconds?  Let's go with an average of 3 API calls in 60 seconds.  That means you can have 600 users on the app at one time before you'll cross your limit.

I'm not taking Parse's cost for granted.  However, I completely disagree that you wouldn't be able to make enough money to cover the costs.  I'll explain my numbers.

If you decided to monetize your app with only AdMob banners, 600 users per minute would give you 1,200 banner impressions if you had them on a 30 second increment.  1,200 impressions per minute is 72,000 per hour and 1,728,000 impressions per day assuming your app get's non-stop traffic.

Let's be conservative and say you have your banners on a 60 second rotation and your app only has an average of 10 hours of peak time.  That's 360,000 daily impressions at $1.00 CPM.  You would make $360 per day and $10,800 per month.  And that's a conservative estimate.  Parse would only cost you $0.  If you had to bump your requests per second up to 60, Parse would only cost you $300 per month.  If you take their slider all the way up to 400 requests per second, you would pay $3,700 per month.  In all scenarios, you'd be able to afford Parse just off of AdMob banners.

If you didn't want to monetize your app with banners or anything else, I'm pretty sure you'd have an easy time finding angel investors to back you.  They love it when your growth is moving so fast that you're blowing through your server limits.  Those are high class problems to have.

**Comment by guillermomuntaner** [comment]
@StormFactory 
First of all, sending push notifications count as 1 Api call too. So as i said, each message sent requires a minimum of 4 Api calls (1 query, 2 saves or more, and 1 push notification). When i am chatting with someone i can send several messages per minute, so lets say 3. Thats already 12Api calls/minute just from one active user. 

With the 1800req/min free cuota, thats 150 concurrent users.  Then, with each 600req/min cuota blocks (each costs 100$/month) you can have 50 more concurrent users. And I am not even counting all the other Api calls required to refresh/join/create/...

For me its no that clear that this is truly scalable and thats why I am asking (to the author probably) the real numbers he is seeing.

**Comment by StormFactory** [comment]
@guillermomuntaner You may be right about the push notifications counting against the limits.  I might have been thinking about Parse Analytics not counting against your API limits.

I don't know your timeline to get a clear financial answer, but I'm moving my Firebase-based chat app to Parse using some of Notification chat.  The app has roughly 2,000 to 3,000 downloads with zero on marketing.  One I make the switch and the app is approved, that number could quickly grow by 10x to 50x because I'll finally start a little marketing push and the target audience could get extremely active.  Figure by end of April I should have stats and real numbers on my Parse costs or lack of costs and I'd be happy to share them.

**Comment by emilypriddy** [comment]
@StormFactory I would be very interested to hear the numbers you get back if you are still willing to share them. Thanks!
